default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: biovision_gem
  #username: test_app
  #password:
  #host: localhost
  #port: 5432
  #schema_search_path: myapp,sharedapp,public
  #min_messages: notice

test:
  <<: *default
  database: biovision_gem_test

production:
  <<: *default
  database: biovision_gem
  username: biovision
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost
